/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.studentloginsystem.pos.view;

import com.studentloginsystem.model.Student;
import com.studentloginsystem.pos.controller.StudentController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DINUKA
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginUI01
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginFormBtn = new javax.swing.JButton();
        bottomtxt = new javax.swing.JLabel();
        signinBtn = new javax.swing.JButton();
        signInPwdField = new javax.swing.JPasswordField();
        pwdTxt = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        idTxt = new javax.swing.JLabel();
        signintxt = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFormBtn.setBackground(new java.awt.Color(0, 204, 204));
        loginFormBtn.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        loginFormBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginFormBtn.setText("Log In");
        loginFormBtn.addActionListener(this::loginFormBtnActionPerformed);
        jPanel1.add(loginFormBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 180, 40));

        bottomtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottomtxt.setForeground(new java.awt.Color(0, 0, 0));
        bottomtxt.setText("Don't have an account ?");
        jPanel1.add(bottomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 220, 40));

        signinBtn.setBackground(new java.awt.Color(0, 204, 204));
        signinBtn.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        signinBtn.setForeground(new java.awt.Color(0, 0, 0));
        signinBtn.setText("Sign Up");
        signinBtn.addActionListener(this::signinBtnActionPerformed);
        jPanel1.add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 180, 40));

        signInPwdField.setBackground(new java.awt.Color(204, 204, 204));
        signInPwdField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signInPwdField.setForeground(new java.awt.Color(0, 0, 0));
        signInPwdField.addActionListener(this::signInPwdFieldActionPerformed);
        jPanel1.add(signInPwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 320, 40));

        pwdTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        pwdTxt.setForeground(new java.awt.Color(0, 0, 0));
        pwdTxt.setText("Password");
        jPanel1.add(pwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 200, 40));

        idInput.setBackground(new java.awt.Color(204, 204, 204));
        idInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 320, 40));

        idTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        idTxt.setText("Student ID");
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 200, 40));

        signintxt.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 48)); // NOI18N
        signintxt.setForeground(new java.awt.Color(0, 0, 0));
        signintxt.setText("Log IN");
        jPanel1.add(signintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 60));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\DINUKA\\Downloads\\pexels-ferhan-575427859-35640792.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInPwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInPwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInPwdFieldActionPerformed

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:
        SignUpForm signupForm = new SignUpForm();
        signupForm.setLocationRelativeTo(null);
        signupForm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_signinBtnActionPerformed

    private void loginFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFormBtnActionPerformed
        try {
            // TODO add your handling code here:
            int stdID = Integer.parseInt(idInput.getText());
            String pwd = new String(signInPwdField.getPassword());
            
            Student loggedStd = StudentController.logIn(stdID);
            
            if(loggedStd != null){
                if(loggedStd.getPwd().equals(pwd)){
                    JOptionPane.showMessageDialog(rootPane, "Logged Successfully "+loggedStd.getfName());
                } else{
                    JOptionPane.showMessageDialog(rootPane, "Password not matched!");
                }
            } else{
                JOptionPane.showMessageDialog(rootPane, "No account found. Please create an account!");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    }//GEN-LAST:event_loginFormBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottomtxt;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginFormBtn;
    private javax.swing.JLabel pwdTxt;
    private javax.swing.JPasswordField signInPwdField;
    private javax.swing.JButton signinBtn;
    private javax.swing.JLabel signintxt;
    // End of variables declaration//GEN-END:variables
}
