/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.studentloginsystem.pos.view;

import com.studentloginsystem.model.Student;
import com.studentloginsystem.pos.controller.StudentController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DINUKA
 */
public class SignUpForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpForm.class.getName());

    /**
     * Creates new form LoginUI01
     */
    public SignUpForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginFormBtn = new javax.swing.JButton();
        bottomtxt = new javax.swing.JLabel();
        signinBtn = new javax.swing.JButton();
        signInPwdField = new javax.swing.JPasswordField();
        pwdTxt = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        idTxt = new javax.swing.JLabel();
        contactTxt = new javax.swing.JLabel();
        contactInput = new javax.swing.JTextField();
        emailTxt = new javax.swing.JLabel();
        mailInput = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        fNameTxt = new javax.swing.JLabel();
        fNameInput = new javax.swing.JTextField();
        signintxt = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginFormBtn.setBackground(new java.awt.Color(0, 204, 204));
        loginFormBtn.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        loginFormBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginFormBtn.setText("Log In");
        loginFormBtn.addActionListener(this::loginFormBtnActionPerformed);
        jPanel1.add(loginFormBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 180, 40));

        bottomtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bottomtxt.setForeground(new java.awt.Color(0, 0, 0));
        bottomtxt.setText("Already have an account ?");
        jPanel1.add(bottomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 220, 40));

        signinBtn.setBackground(new java.awt.Color(0, 204, 204));
        signinBtn.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        signinBtn.setForeground(new java.awt.Color(0, 0, 0));
        signinBtn.setText("Sign Up");
        signinBtn.addActionListener(this::signinBtnActionPerformed);
        jPanel1.add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 180, 40));

        signInPwdField.setBackground(new java.awt.Color(204, 204, 204));
        signInPwdField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signInPwdField.setForeground(new java.awt.Color(0, 0, 0));
        signInPwdField.addActionListener(this::signInPwdFieldActionPerformed);
        jPanel1.add(signInPwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 320, 40));

        pwdTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        pwdTxt.setForeground(new java.awt.Color(0, 0, 0));
        pwdTxt.setText("Password");
        jPanel1.add(pwdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 200, 40));

        idInput.setBackground(new java.awt.Color(204, 204, 204));
        idInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 320, 40));

        idTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        idTxt.setText("Student ID");
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 200, 40));

        contactTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(0, 0, 0));
        contactTxt.setText("Contact Number");
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 40));

        contactInput.setBackground(new java.awt.Color(204, 204, 204));
        contactInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contactInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(contactInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 320, 40));

        emailTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(0, 0, 0));
        emailTxt.setText("Email");
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 40));

        mailInput.setBackground(new java.awt.Color(204, 204, 204));
        mailInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mailInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(mailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 320, 40));

        lastNameTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lastNameTxt.setForeground(new java.awt.Color(0, 0, 0));
        lastNameTxt.setText("Last Name");
        jPanel1.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 200, 40));

        lastNameInput.setBackground(new java.awt.Color(204, 204, 204));
        lastNameInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lastNameInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lastNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 320, 40));

        fNameTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        fNameTxt.setForeground(new java.awt.Color(0, 0, 0));
        fNameTxt.setText("First Name");
        jPanel1.add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 40));

        fNameInput.setBackground(new java.awt.Color(204, 204, 204));
        fNameInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fNameInput.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 320, 40));

        signintxt.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 36)); // NOI18N
        signintxt.setForeground(new java.awt.Color(0, 0, 0));
        signintxt.setText("Sign UP");
        jPanel1.add(signintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 170, 40));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\DINUKA\\Downloads\\pexels-ferhan-575427859-35640792.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInPwdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInPwdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInPwdFieldActionPerformed

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:
        String fName = fNameInput.getText();
        String lName = lastNameInput.getText();
        String email = mailInput.getText();
        String contact = contactInput.getText();
        int id = Integer.parseInt(idInput.getText());
        String pwd = new String(signInPwdField.getPassword());
        
        Student std = new Student(fName, lName, email, contact, id, pwd);
        
        try {
            boolean result = StudentController.signIn(std);
            if (result){
                JOptionPane.showMessageDialog(rootPane, "Successfully Signed In");
                clearInputs();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sign In Unsuccessful!");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_signinBtnActionPerformed

    private void loginFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFormBtnActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setLocationRelativeTo(null);
        loginForm.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_loginFormBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpForm().setVisible(true));
    }
    
    public void clearInputs(){
        fNameInput.setText("");
        lastNameInput.setText("");
        mailInput.setText("");
        contactInput.setText("");
        idInput.setText("");
        signInPwdField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottomtxt;
    private javax.swing.JTextField contactInput;
    private javax.swing.JLabel contactTxt;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JTextField fNameInput;
    private javax.swing.JLabel fNameTxt;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameTxt;
    private javax.swing.JButton loginFormBtn;
    private javax.swing.JTextField mailInput;
    private javax.swing.JLabel pwdTxt;
    private javax.swing.JPasswordField signInPwdField;
    private javax.swing.JButton signinBtn;
    private javax.swing.JLabel signintxt;
    // End of variables declaration//GEN-END:variables
}
